include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**.g.dart"

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
